exclude = [
  'https://atlas-talk\.sdcc\.bnl\.gov/', # 400
  'https://docs\.google\.com/spreadsheets/d/1caEe8zdOblo_qufUgIYpL0nqMcjI4l37TZNvDTLLtTw',  # 401
  'https://doi\.org/10\.1103/PhysRevD\.94\.032003', # 403
  'https://.+\.aps\.org/.+', # 403 for APS
]
